# Generated by Django 6.1.1 on 2026-09-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_studentprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('internship', 'Internship'), ('freelance', 'Freelance')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_format', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=10)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('compensation', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='users.companyprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='opportunities', to='users.skill')),
            ],
        ),
    ]
