# Generated by Django 6.1.1 on 2026-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
